"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import os
import logging
import dj_database_url
import sentry_sdk
from sentry_sdk.integrations.django import DjangoIntegration
from dotenv import load_dotenv

logger = logging.getLogger(__name__)

# Load environment variables from .env file
# Load environment variables from .env file
load_dotenv()

# Initialize Sentry
SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        traces_sample_rate=0.1,
        send_default_pii=True
    )

logger.debug("DEBUG: Environment Keys: %s", sorted([k for k in os.environ.keys()]))
logger.debug("DEBUG: DATABASE_URL is present: %s", 'DATABASE_URL' in os.environ)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# CHANGED: Remove hard-coded insecure key and require SECRET_KEY in production
# For development, generate a temporary key. In production, set via env var.
SECRET_KEY = os.getenv('SECRET_KEY')

if not SECRET_KEY:
    if os.getenv('DEBUG', 'False') == 'True':
        # Development: auto-generate a throwaway key (not persisted)
        import secrets
        SECRET_KEY = secrets.token_urlsafe(50)
    else:
        # Production: MUST have SECRET_KEY set; fail fast
        raise ValueError(
            "ERROR: SECRET_KEY environment variable is required in production. "
            "Generate one with: python -c \"import secrets; print(secrets.token_urlsafe(50))\" "
            "and set it in your deployment environment."
        )

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'vunachainlanding-production.up.railway.app',
    '.up.railway.app',
    'vunachain.com',
    'www.vunachain.com',
    '.vunachain.com',
]

# Allow all hosts on Railway to allow internal health checks (Edge proxy protects us)
if os.getenv('RAILWAY_ENVIRONMENT_NAME'):
    ALLOWED_HOSTS = ['*']

# Exempt health check from SSL redirect (Railway checks via HTTP internally)
SECURE_REDIRECT_EXEMPT = [r'^api/health/$']

# Allow additional hosts from environment variable (comma-separated)
extra_hosts = os.getenv('ALLOWED_HOSTS')
if extra_hosts:
    ALLOWED_HOSTS.extend([host.strip() for host in extra_hosts.split(',') if host.strip()])


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Local apps
    'lead_capture',
    'blockchain_sync',
    'blockchain',
    'user_management',
]

# Add GeoDjango only when PostGIS is available (production)
if os.getenv('DATABASE_URL', '').startswith('postgres'):
    INSTALLED_APPS.insert(INSTALLED_APPS.index('rest_framework'), 'django.contrib.gis')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS MUST be at the very top
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database Configuration
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
# Database Configuration
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Robust DATABASE_URL detection
# Some platforms use different names or sometimes DATABASE_URL is empty
DATABASE_URL = os.getenv('DATABASE_URL') or os.getenv('POSTGRES_URL') or os.getenv('PGURL')

# Check if we are on Railway
IS_RAILWAY = os.getenv('RAILWAY_ENVIRONMENT_NAME') is not None

# Debug print to inspect DATABASE_URL safely
if DATABASE_URL:
    # Log ONLY the start to avoid leaking credentials
    logger.debug("DATABASE_URL detected. Starts with: %s...", DATABASE_URL[:15])
else:
    logger.debug("DATABASE_URL is None or empty. (Checked: DATABASE_URL, POSTGRES_URL, PGURL)")

try:
    if DATABASE_URL and len(DATABASE_URL.strip()) > 0:
        if '://' not in DATABASE_URL:
             raise ValueError(f"DATABASE_URL is missing scheme (://). Value starts with: {DATABASE_URL[:50]}...")
        
        DATABASES = {
            'default': dj_database_url.config(
                default=DATABASE_URL,
                conn_max_age=600,
                conn_health_checks=True,
                engine='django.contrib.gis.db.backends.postgis' if DATABASE_URL.startswith('postgres') else None
            )
        }
        logger.debug("Configured DB Engine: %s", DATABASES['default']['ENGINE'])
    else:
        # If on Railway, this is a fatal error
        if IS_RAILWAY:
            msg = "FATAL ERROR: DATABASE_URL is MISSING or EMPTY on Railway! Please link your Postgres service to your Backend service in the Railway dashboard."
            print(msg)
            # Fail fast to avoid cryptic errors later
            import sys
            sys.exit(1)
        
        raise ValueError("DATABASE_URL is not set")
except Exception as e:
    if IS_RAILWAY:
        # Re-raise or exit because we already handled the exit above for empty URL
        # If it's a parse error, we should still exit.
        print(f"FATAL ERROR during DB Parse: {e}")
        import sys
        sys.exit(1)
        
    print(f"CRITICAL: Database configuration failed: {e}. Falling back to ephemeral SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }

# Use PostGIS engine if using PostgreSQL
if DATABASES['default'].get('ENGINE') == 'django.db.backends.postgresql':
    DATABASES['default']['ENGINE'] = 'django.contrib.gis.db.backends.postgis'


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
WHITENOISE_MANIFEST_STRICT = False  # Prevent crash when source maps are missing

STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# CORS_ALLOW_ALL_ORIGINS is intentionally NOT set to True — use CORS_ALLOWED_ORIGINS whitelist below
CORS_ALLOWED_ORIGINS = [
    'https://vunachain.com',
    'https://www.vunachain.com',
    'https://vunachainlanding-production.up.railway.app',
    'http://localhost:3000',
    'http://localhost:5173',
]

CORS_ALLOWED_ORIGIN_REGEXES = [
    r"^https://.*\.vercel\.app$",
]

# Allow additional origins from environment variable (comma-separated)
_extra_origins = os.getenv('CORS_ALLOWED_ORIGINS', '')
if _extra_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in _extra_origins.split(',') if origin.strip()])

CORS_ALLOW_CREDENTIALS = True
CORS_PREFLIGHT_MAX_AGE = 86400  # 1 day

CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Trusted origins for CSRF (required for POST requests in Django 4+)
CSRF_TRUSTED_ORIGINS = [
    'https://vunachain.com',
    'https://www.vunachain.com',
    'https://vunachainlanding-production.up.railway.app',
    'https://vunachainbackend-production.up.railway.app',
    'http://localhost:3000',
]

# Allow CSRF to work with CORS for public APIs
# CORS_REPLACE_HTTPS_REFERER = True  # Removed: Deprecated in django-cors-headers
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]



# Django REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ],
    # Use JWT for authentication
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Throttling to prevent abuse
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '100/hour',
        'user': '1000/hour',
    },
}

from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
}

# Production Security Hardening
if not DEBUG:
    # 1. Force HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # 2. Strict Transport Security (HSTS)
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # 3. Secure Cookies
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # 4. Browser Security Headers
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True  # Deprecated in modern browsers but useful legacy
    SECURE_REFERRER_POLICY = 'strict-origin-when-cross-origin'
    
    # 5. X-Frame-Options
    X_FRAME_OPTIONS = 'DENY'

# Jazzmin Settings
JAZZMIN_SETTINGS = {
    "site_title": "Vunachain Admin",
    "site_header": "Vunachain",
    "site_brand": "Vunachain Compliance",
    "site_logo": None,  # Removed missing logo reference to fix 500 error
    "login_logo": None,
    "login_logo_dark": None,
    "site_logo_classes": "img-circle",
    "add_section_classes": "btn-primary",
    "change_section_classes": "btn-success",
    "welcome_sign": "Welcome to the Vunachain Admin Dashboard",
    "copyright": "Vunachain Ltd",
    "search_model": ["lead_capture.DemoRequest", "lead_capture.EmailSubscription"],
    "user_avatar": None,
    "topmenu_links": [
        {"name": "Home", "url": "admin:index", "permissions": ["auth.view_user"]},
        {"name": "Support", "url": "https://vunachain.com/support", "new_window": True},
        {"model": "auth.User"},
        {"label": "Support", "url": "https://vunachain.com/support", "new_window": True},
    ],
    "show_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "order_with_respect_to": ["lead_capture", "auth"],
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "lead_capture.DemoRequest": "fas fa-handshake",
        "lead_capture.EmailSubscription": "fas fa-envelope",
        "lead_capture.ROICalculation": "fas fa-calculator",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    "related_modal_active": False,
    "custom_js": None,
    "show_ui_builder": False,
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {"auth.user": "collapsible_list", "auth.group": "vertical_tabs"},
}

JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-dark",
    "accent": "accent-primary",
    "navbar": "navbar-dark",
    "no_navbar_border": False,
    "navbar_fixed": False,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": False,
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-success"
    }
}

# Celo Blockchain Configuration
CELO_RPC_URL = os.getenv("CELO_RPC_URL", "https://forno.celo.org")
CELO_WEBSOCKET_URL = os.getenv("CELO_WEBSOCKET_URL", "wss://forno.celo.org/ws")
CELO_SEPOLIA_RPC_URL = os.getenv("CELO_SEPOLIA_RPC_URL", "https://forno.celo-sepolia.celo-testnet.org")
CELO_SEPOLIA_WEBSOCKET_URL = os.getenv("CELO_SEPOLIA_WEBSOCKET_URL", "wss://forno.celo-sepolia.celo-testnet.org/ws")
# Contract addresses should be added here after deployment


