# Generated by Django 5.0.1 on 2026-03-27 19:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MerkleBatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merkle_root', models.CharField(db_index=True, max_length=66, unique=True)),
                ('total_records', models.PositiveIntegerField()),
                ('total_amount_cusd', models.DecimalField(decimal_places=18, help_text='Total payout in cUSD', max_digits=30)),
                ('transaction_hash', models.CharField(blank=True, help_text='Transaction hash of createBatchPayout', max_length=66, null=True)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('CONFIRMED', 'Confirmed')], default='CREATED', max_length=20)),
                ('is_distributed', models.BooleanField(default=False, help_text='True if batch was directly distributed by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Merkle Batch',
                'verbose_name_plural': 'Merkle Batches',
            },
        ),
        migrations.CreateModel(
            name='Cooperative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manager', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_cooperative', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FarmerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celo_address', models.CharField(db_index=True, max_length=42, unique=True)),
                ('phone_number', models.CharField(help_text='Format: 254XXXXXXXXX', max_length=15)),
                ('full_name', models.CharField(max_length=200)),
                ('national_id', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ('kyc_data', models.JSONField(blank=True, default=dict, help_text='KYC documents and metadata')),
                ('credit_score', models.IntegerField(default=0, help_text='Calculated credit score (0-1000)')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmers', to='blockchain_sync.cooperative')),
            ],
            options={
                'verbose_name': 'Farmer Profile',
                'verbose_name_plural': 'Farmer Profiles',
            },
        ),
        migrations.CreateModel(
            name='OnChainHarvest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.PositiveIntegerField(help_text='Blockchain record ID', unique=True)),
                ('farmer_address', models.CharField(help_text='Celo wallet address of the farmer', max_length=42)),
                ('farmer_id', models.CharField(blank=True, help_text='Backend UUID of the farmer', max_length=100, null=True)),
                ('crop_type', models.CharField(max_length=100)),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('location', models.CharField(help_text='Geographic location string', max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Verified'), (2, 'Rejected'), (3, 'Paid')], default=0)),
                ('payout_amount_cusd', models.DecimalField(decimal_places=18, default=0, max_digits=32)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('transaction_hash', models.CharField(blank=True, help_text='On-chain verification TX hash', max_length=66, null=True)),
                ('merkle_proof', models.JSONField(blank=True, help_text='Merkle proof for batch payout claim', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='harvests', to='blockchain_sync.merklebatchmodel')),
            ],
            options={
                'verbose_name_plural': 'On-Chain Harvests',
            },
        ),
        migrations.CreateModel(
            name='MpesaPayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text="Farmer's phone number for M-Pesa", max_length=15)),
                ('amount_kes', models.DecimalField(decimal_places=2, help_text='Converted payout in KES', max_digits=12)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('INITIATED', 'Initiated'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('conversion_rate', models.DecimalField(decimal_places=4, help_text='cUSD to KES rate used', max_digits=10)),
                ('originator_conversation_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('conversation_id', models.CharField(blank=True, max_length=100, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('initiated_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('harvest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout', to='blockchain_sync.onchainharvest')),
            ],
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Main Plot', max_length=100)),
                ('boundary', models.JSONField(help_text='Boundary coordinates (GeoJSON Polygon formatted)')),
                ('area_hectares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_eudr_compliant', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cooperative', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plots', to='blockchain_sync.cooperative')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots', to='blockchain_sync.farmerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FarmEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('PLANTING', 'Planting'), ('SPRAYING', 'Spraying'), ('HARVESTING', 'Harvesting'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.JSONField(blank=True, help_text='GPS capture of the event (GeoJSON Point format)', null=True)),
                ('photo_url', models.URLField(blank=True, help_text='URL to photo evidence', max_length=500, null=True)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'Grade A (Premium)'), ('B', 'Grade B (Standard)'), ('C', 'Grade C (Low)'), ('REJECTED', 'Rejected')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('farmos_uuid', models.UUIDField(blank=True, help_text='Reference to farmOS log UUID', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blockchain_sync.farmerprofile')),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='blockchain_sync.plot')),
            ],
            options={
                'verbose_name': 'Farm Event',
                'verbose_name_plural': 'Farm Events',
                'ordering': ['-timestamp'],
            },
        ),
    ]
