# Generated by Django 5.0.1 on 2026-03-27 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain_sync', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupplyContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commodity', models.CharField(help_text='e.g. Arabica Coffee, Macadamia', max_length=100)),
                ('target_volume_kg', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_per_kg_cusd', models.DecimalField(decimal_places=4, max_digits=10)),
                ('quality_specs', models.TextField(help_text='e.g. Moisture < 12%, Grade AA')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open (Awaiting Coop)'), ('ACTIVE', 'Active (Allocated)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_contracts', to=settings.AUTH_USER_MODEL)),
                ('cooperative', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='blockchain_sync.cooperative')),
            ],
            options={
                'verbose_name': 'Supply Contract',
                'verbose_name_plural': 'Supply Contracts',
                'ordering': ['-created_at'],
            },
        ),
    ]
