# Generated by Django 5.0.1 on 2026-02-02 16:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the requester', max_length=200)),
                ('email', models.EmailField(help_text='Work email address', max_length=254)),
                ('company', models.CharField(help_text='Company name', max_length=200)),
                ('interest', models.CharField(choices=[('compliance', 'EUDR Compliance'), ('sideselling', 'Stopping Side-Selling'), ('finance', 'Input Finance Recovery'), ('other', 'General Demo')], default='compliance', help_text='Primary area of interest', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Submission timestamp')),
            ],
            options={
                'verbose_name': 'Demo Request',
                'verbose_name_plural': 'Demo Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Subscriber email address', max_length=254, unique=True)),
                ('source', models.CharField(choices=[('footer', 'Footer Form'), ('exit_intent', 'Exit Intent Modal'), ('hero', 'Hero Section')], default='footer', help_text='Source of subscription', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Subscription timestamp')),
                ('is_active', models.BooleanField(default=True, help_text='Active subscription status')),
            ],
            options={
                'verbose_name': 'Email Subscription',
                'verbose_name_plural': 'Email Subscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ROICalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_volume', models.IntegerField(help_text='Annual tonnage entered by user (MT)')),
                ('calculated_loss', models.DecimalField(decimal_places=2, help_text='Calculated loss value in USD', max_digits=12)),
                ('crop_type', models.CharField(default='Coffee', help_text='Crop type selected (e.g., Coffee, Cocoa, Avocado)', max_length=50)),
                ('session_id', models.CharField(blank=True, help_text='Browser session ID for tracking multiple interactions', max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Interaction timestamp')),
            ],
            options={
                'verbose_name': 'ROI Calculation',
                'verbose_name_plural': 'ROI Calculations',
                'ordering': ['-created_at'],
            },
        ),
    ]
