# Generated by Django 5.0.1 on 2026-02-06 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demorequest',
            name='location_point',
            field=models.CharField(blank=True, help_text='Captured location (Point)', max_length=100, null=True),
        ),
    ]
