# Generated by Django 5.0.1 on 2026-02-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lead_capture', '0002_demorequest_location_point'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demorequest',
            name='interest',
            field=models.CharField(choices=[('compliance', 'EUDR, Tea Act 2020 & Rainforest Alliance'), ('sideselling', 'Stopping Side-Selling'), ('finance', 'Input Finance Recovery'), ('partner', 'Partner with us'), ('other', 'General Demo')], default='compliance', help_text='Primary area of interest', max_length=50),
        ),
    ]
